[features]
seeds = false
skip-lint = false
[programs.localnet]
wba_vault = "4TLhT3e1bn8UcSg6qQScKhWi1LwEy52yy7cFn6J1rt7S"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/home/beliv/wba/q2starter/solana-Q2-starter/ts/wba-wallet.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
